### ISSUE TITLE
Feature: Support cli argument for .ca location

### ISSUE THREAD

**Issue by adamboutcher** [stfc/CertWizard#34]
Support argument for changing the .ca location so it doesn't nag every startup.

I store my .ca directory somewhere other than home and every time I load CertWizard, I have to manually find the location in a sea of (hidden dot) directories.

**Comment by willfurnell** [comment]
Currently looking into this - sorry for such a long wait.

**Comment by willfurnell** [comment]
@adamboutcher I have made this feature - and it will be available in the next release - probably this week once we've done some more internal testing :)

**Comment by willfurnell** [comment]
The latest release now supports this feature!

**Comment by adamboutcher** [comment]
Hi, Sorry for such a late reply. I've finally updated however, how do I specify the location as an argument?

**Comment by willfurnell** [comment]
Sorry for my late reply! Yes that works. Also, the directory no longer needs to be named `.ca` - it can be any name and everything should work OK.
